import { MetadataRoute } from 'next';

export default function sitemap() {
  const baseUrl = 'https://top-phim.pro';
  const lastMod = '2024-09-14T00:00:00+00:00';
  return [
    {
      url: `${baseUrl}`,
      lastModified: '2024-09-14',
      changeFrequency: 'hourly',
      priority: 1.0
    },
    {
      url: `${baseUrl}/phim-le`,
      lastModified: '2024-09-14',
      changeFrequency: 'daily',
      priority: 0.9
    },
    {
      url: `${baseUrl}/phim-bo`,
      lastModified: '2024-09-14',
      changeFrequency: 'daily',
      priority: 0.9
    },
    {
      url: `${baseUrl}/phim-moi`,
      lastModified: '2024-09-14',
      changeFrequency: 'daily',
      priority: 0.9
      },
      {
        url: `${baseUrl}/tv-shows`,
        lastModified: '2024-09-14',
        changeFrequency: 'daily',
        priority: 0.9
      },
      {
        url: `${baseUrl}/hoat-hinh`,
        lastModified: '2024-09-14',
        changeFrequency: 'daily',
        priority: 0.9
      },
      {
        url: `${baseUrl}/the-loai/hanh-dong`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/tinh-cam`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/hai-huoc`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/co-trang`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/tam-ly`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/hinh-su`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/chien-tranh`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/the-thao`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/vo-thuat`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/vien-tuong`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/phieu-luu`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/khoa-hoc`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/kinh-di`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/am-nhac`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/than-thoai`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/tai-lieu`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/gia-dinh`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/chinh-kich`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/bi-an`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/hoc-duong`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/kinh-dien`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      {
        url: `${baseUrl}/the-loai/phim-18`,
        lastModified: lastMod,
        changeFrequency: 'daily',
        priority: 0.9,
      },
      { url: "https://top-phim.pro/quoc-gia/Trung-Quoc", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Han-Quoc", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Nhat-Ban", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Thai-Lan", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Au-My", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Dai-Loan", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Hong-Kong", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/An-Do", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Anh", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Phap", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Canada", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Quoc-Gia-Khac", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Duc", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Tay-Ban-Nha", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Tho-Nhi-Ky", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Han-Lan", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Indonesia", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Nga", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Mexico", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Ba-Lan", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Uc", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Thuy-Dien", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Malaysia", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Brazil", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Philippines", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Bo-Dao-Nha", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Y", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Dan-Mach", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/UAE", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Na-Uy", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Thuy-Si", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Chau-Phi", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Nam-Phi", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Ukraina", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/A-Rap-Xe-Ut", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Bi", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Ireland", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Colombia", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Phan-Lan", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Viet-Nam", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Chile", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  { url: "https://top-phim.pro/quoc-gia/Hy-Lap", lastModified: "2024-09-14", changeFrequency: daily, priority: 0.9 },
  ];
}
